sudo: required

services: docker

before_install:
    - echo "Building client image..."
    - docker build -t $DOCKER_ID/react-frontend:latest .

script:
    - echo "Running tests..."
    - docker run -e CI=true $DOCKER_ID/react-frontend:latest yarn test

after_success:
    - echo "Pushing image to Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $DOCKER_ID/react-frontend:latest

# deploy:
#     provider: elasticbeanstalk
#     region: us-east-1
#     app: string-reverser
#     env: StringReverser-env
#     bucket_name: elasticbeanstalk-us-east-1-784282585398
#     bucket_path: string-reverser
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     on:
#         branch: master